from __future__ import annotations


USO_CFDI_OPCIONES = [
    "G01", "G02", "G03",
    "I01", "I02", "I03", "I04", "I05", "I06", "I07", "I08",
    "D01", "D02", "D03", "D04", "D05", "D06", "D07", "D08", "D09", "D10",
    "S01",
]

FORMA_PAGO_OPCIONES = [
    "EFECTIVO",
    "CHEQUE NOMINATIVO",
    "TRANSFERENCIA ELECTRONICA DE FONDOS",
    "TARJETA DE CREDITO",
    "TARJETA DE DEBITO",
    "POR DEFINIR",
]

PROVEEDORES_OPCIONES = [
    "MITAFSA", "BETANSA", "ARGONZA", "REKLAMSA", "ERF", "EDETESA", "XISISA", "GEREDAB", "TIKSA",
    "VIESA", "DIAFIMSA", "ARMOLEB", "JOVIC", "COLMEXL", "MARTO",
]
